version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  frontend:
    image: ghcr.io/seaweedbraincy/frontend_bad_cors:latest
    container_name: frontend
    ports:
      - "127.0.0.1:8000:4200"
  api:
    image: ghcr.io/seaweedbraincy/api_bad_cors:latest
    container_name: api
    ports:
      - "127.0.0.1:8001:80"
  api_safe:
    image: ghcr.io/seaweedbraincy/api_bad_cors:latest
    container_name: api_safe
    ports:
      - "127.0.0.1:8002:80"
    environment:
      - ENVIRONMENT=safe