version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  frontend:
    image: ghcr.io/seaweedbraincy/frontend_rce:latest
    container_name: frontend
    ports:
      - "8000:8080"
  frontend_safe:
    image: ghcr.io/seaweedbraincy/safe_frontend:latest
    container_name: frontend_safe
    ports:
      - "8003:8080"
  api:
    image: ghcr.io/seaweedbraincy/api_rce:latest
    container_name: api
    ports:
      - "8001:80"
  api_safe:
    image: ghcr.io/seaweedbraincy/safe_api_rce:latest
    container_name: api_safe
    ports:
      - "8002:80"