version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "9000:9000"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  frontend:
    image: ghcr.io/seaweedbraincy/frontend_badauth:latest
    container_name: frontend
    ports:
      - "8000:8080"
  api:
    image: ghcr.io/seaweedbraincy/api_badauth:latest
    container_name: api
    ports:
      - "8001:80"
  api_safe:
    image: ghcr.io/seaweedbraincy/safe_api_badauth:latest
    container_name: api_safe
    ports:
      - "8002:80"