version: '3'

services:
  frontend:
    image: ghcr.io/seaweedbraincy/frontend_badauth:latest
    container_name: frontend
    ports:
      - "8003:80"
  api:
    image: ghcr.io/seaweedbraincy/api_badauth:latest
    container_name: api
    ports:
      - "8001:80"
  api_safe:
    image: ghcr.io/seaweedbraincy/safe_api_badauth:latest
    container_name: api_safe
    ports:
      - "8002:80"