version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  frontend:
    image: ghcr.io/seaweedbraincy/frontend_ssrf:latest
    container_name: frontend
    ports:
      - "8000:80"
  api:
    image: ghcr.io/seaweedbraincy/api_ssrf:latest
    container_name: api
    ports:
      - "8001:80"