---
- name: Déployer et exécuter Docker Compose
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: send docker install script
      copy:
        src: ./script.sh
        dest: /root/script.sh
        mode: '0755'  # Assurez-vous que le script est exécutable

    - name: Installing docker
      command: /root/script.sh

    - name: Send docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /root/docker-compose.yml
    
    - name: Send nginx.conf
      copy:
        src: ./nginx.conf
        dest: /root/nginx.conf

    - name: Stopping current containers
      command: docker compose down 
      args:
        chdir: /root


    - name: Pulling images
      command: docker compose pull 
      args:
        chdir: /root

    - name: Starting containers
      command: docker compose up -d
      args:
        chdir: /root