name: API with bad CORS

on:
  push:
     tags: [ 'cors.*' ]

env:
    IMAGE_NAME: "api_bad_cors"

jobs:
  build-and-publish:
    name: Build and Publish API Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./api_bad_CORS/
      run: docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin
    - name: Push Docker image to GitHub Container Registry
      run: |
            docker tag $IMAGE_NAME:latest ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.sha }}
            docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
            docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.sha }}
